name: CI

on: [push, pull_request]

jobs:
  shell:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt-get install -y make shellcheck 

      - name: Check
        run: make clean check

  PowerShell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: .\millw.ps1
          enableExit: true
